var postes = {
"type": "FeatureCollection",
"name": "postes_luz",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "cat": 8, "osm_id": "10043982162", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8972259, 9.8557217 ] } },
{ "type": "Feature", "properties": { "cat": 9, "osm_id": "10043982163", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8969085, 9.8560286 ] } },
{ "type": "Feature", "properties": { "cat": 10, "osm_id": "10043982164", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8965175, 9.8563995 ] } },
{ "type": "Feature", "properties": { "cat": 11, "osm_id": "10043982165", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8964756, 9.8564443 ] } },
{ "type": "Feature", "properties": { "cat": 12, "osm_id": "10043982166", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8969339, 9.8569369 ] } },
{ "type": "Feature", "properties": { "cat": 13, "osm_id": "10043982167", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8967218, 9.8567038 ] } },
{ "type": "Feature", "properties": { "cat": 14, "osm_id": "10043982168", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8975495, 9.8561113 ] } },
{ "type": "Feature", "properties": { "cat": 15, "osm_id": "10043982169", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8978846, 9.8564575 ] } },
{ "type": "Feature", "properties": { "cat": 16, "osm_id": "10043982170", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8981473, 9.8567188 ] } },
{ "type": "Feature", "properties": { "cat": 17, "osm_id": "pole", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8984003, 9.8569519 ] } },
{ "type": "Feature", "properties": { "cat": 18, "osm_id": "10043982173", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8981467, 9.8573275 ] } },
{ "type": "Feature", "properties": { "cat": 19, "osm_id": "10043982174", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8978409, 9.8569944 ] } },
{ "type": "Feature", "properties": { "cat": 20, "osm_id": "10043982175", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8975715, 9.8567207 ] } },
{ "type": "Feature", "properties": { "cat": 21, "osm_id": "10043982176", "name": null, "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "pole" }, "geometry": { "type": "Point", "coordinates": [ -83.8972638, 9.8564205 ] } }
]
};
